version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ES_VERSION: $ES_VERSION
        SG_PLUGIN_VERSION: $SG_PLUGIN_VERSION
        SG_SSL_PLUGIN_VERSION: $SG_SSL_PLUGIN_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/sg_config.yml:/usr/share/elasticsearch/config/sg_config.yml
      - ./elasticsearch/config/sg_action_groups.yml:/usr/share/elasticsearch/config/sg_action_groups.yml
      - ./elasticsearch/config/sg_internal_users.yml:/usr/share/elasticsearch/config/sg_internal_users.yml
      - ./elasticsearch/config/sg_roles_mapping.yml:/usr/share/elasticsearch/config/sg_roles_mapping.yml
      - ./elasticsearch/config/sg_roles.yml:/usr/share/elasticsearch/config/sg_roles.yml
      - ./elasticsearch/config/truststore.jks:/usr/share/elasticsearch/config/truststore.jks
      - ./elasticsearch/config/kirk-keystore.jks:/usr/share/elasticsearch/config/kirk-keystore.jks
      - ./elasticsearch/config/node-0-keystore.jks:/usr/share/elasticsearch/config/node-0-keystore.jks
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  elasticsearch2:
    build:
      context: elasticsearch/
      args:
        ES_VERSION: $ES_VERSION
        SG_PLUGIN_VERSION: $SG_PLUGIN_VERSION
        SG_SSL_PLUGIN_VERSION: $SG_SSL_PLUGIN_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/sg_config.yml:/usr/share/elasticsearch/config/sg_config.yml
      - ./elasticsearch/config/sg_action_groups.yml:/usr/share/elasticsearch/config/sg_action_groups.yml
      - ./elasticsearch/config/sg_internal_users.yml:/usr/share/elasticsearch/config/sg_internal_users.yml
      - ./elasticsearch/config/sg_roles_mapping.yml:/usr/share/elasticsearch/config/sg_roles_mapping.yml
      - ./elasticsearch/config/sg_roles.yml:/usr/share/elasticsearch/config/sg_roles.yml
      - ./elasticsearch/config/truststore.jks:/usr/share/elasticsearch/config/truststore.jks
      - ./elasticsearch/config/kirk-keystore.jks:/usr/share/elasticsearch/config/kirk-keystore.jks
      - ./elasticsearch/config/node-0-keystore.jks:/usr/share/elasticsearch/config/node-0-keystore.jks
    ports:
      - "9202:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        LS_VERSION: $LS_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        KIBANA_VERSION: $KIBANA_VERSION
        SG_KIBANA_PLUGIN_VERSION: $SG_KIBANA_PLUGIN_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
